### ISSUE TITLE
pip install in conda environment not working

### ISSUE THREAD

**Issue by szvsw** [AaltoRSE/ParallelFDTD#5]
Hi --

I am trying to install ParallFDTD for use in Python 3.  On a windows 11 machine with an Nvidia GeForce RTX 3080Ti.

So far I have done the following:

1. Installed the Windows 11 SDK, v10.0.22621 from [here](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/)
2. Installed Anacondas.
3. Run `conda create -n PFDTD -c conda-forge boost py-boost cmake numpy scipy`
4. Activated the conda env

When I run `pip install git+https://github.com/AaltoRSE/ParallelFDTD.git`, I get the following error output, indicating that the `CMAKE_CXX_COMPILER not set, after EnableLanguage` and `CMAKE_CUDA_COMPILER not set, after EnableLanguage`:

```
Collecting git+https://github.com/AaltoRSE/ParallelFDTD.git
  Cloning https://github.com/AaltoRSE/ParallelFDTD.git to c:\users\samwol~1\appdata\local\temp\pip-req-build-uqk4trv_
  Running command git clone --filter=blob:none --quiet https://github.com/AaltoRSE/ParallelFDTD.git 'C:\Users\SAMWOL~1\AppData\Local\Temp\pip-req-build-uqk4trv_'
  Resolved https://github.com/AaltoRSE/ParallelFDTD.git to commit aa8037f1f7f4e645d1bbd036cd79761e2c5ea74f
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyParallelFDTD
  Building wheel for pyParallelFDTD (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\pyParallelFDTD
      copying dist\libPyFDTD\__init__.py -> build\lib.win-amd64-cpython-37\pyParallelFDTD
      running build_ext
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:5 (project):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      See also "C:/Users/Sam Wolk/AppData/Local/Temp/pip-req-build-uqk4trv_/build/temp.win-amd64-cpython-37/Release/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\SAMWOL~1\AppData\Local\Temp\pip-req-build-uqk4trv_\setup.py", line 117, in <module>
          'install_lib': InstallCMakeLibs,
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\SAMWOL~1\AppData\Local\Temp\pip-req-build-uqk4trv_\setup.py", line 72, in run
          self.build_extension(ext)
        File "C:\Users\SAMWOL~1\AppData\Local\Temp\pip-req-build-uqk4trv_\setup.py", line 87, in build_extension
          cmake_config
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-HC:\\Users\\SAMWOL~1\\AppData\\Local\\Temp\\pip-req-build-uqk4trv_', '-Bbuild\\temp.win-amd64-cpython-37\\Release', '-DBUILD_PYTHON=on']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyParallelFDTD
  Running setup.py clean for pyParallelFDTD
Failed to build pyParallelFDTD
Installing collected packages: pyParallelFDTD
  Running setup.py install for pyParallelFDTD ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyParallelFDTD did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running install
      C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-37
      creating build\lib.win-amd64-cpython-37\pyParallelFDTD
      copying dist\libPyFDTD\__init__.py -> build\lib.win-amd64-cpython-37\pyParallelFDTD
      running build_ext
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:5 (project):
        Running

         'nmake' '-?'

        failed with:

         The system cannot find the file specified


      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CUDA_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      See also "C:/Users/Sam Wolk/AppData/Local/Temp/pip-req-build-uqk4trv_/build/temp.win-amd64-cpython-37/Release/CMakeFiles/CMakeOutput.log".
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\SAMWOL~1\AppData\Local\Temp\pip-req-build-uqk4trv_\setup.py", line 117, in <module>
          'install_lib': InstallCMakeLibs,
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\SAMWOL~1\AppData\Local\Temp\pip-req-build-uqk4trv_\setup.py", line 72, in run
          self.build_extension(ext)
        File "C:\Users\SAMWOL~1\AppData\Local\Temp\pip-req-build-uqk4trv_\setup.py", line 87, in build_extension
          cmake_config
        File "C:\ProgramData\Anaconda3\envs\PFDTD\lib\subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-HC:\\Users\\SAMWOL~1\\AppData\\Local\\Temp\\pip-req-build-uqk4trv_', '-Bbuild\\temp.win-amd64-cpython-37\\Release', '-DBUILD_PYTHON=on']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyParallelFDTD

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

The conda env does show that `cmake` is installed, and I also tried installing Cmake manually but the error persisted.

I would really appreciate it if you could point me to the correct way of configuring the cmake compiler so that the conda env is aware of it, since the default instructions do not seem to be working.

Thanks!

**Comment by szvsw** [comment]
I was able to make *some* progress but still not fully successful.  

- Installing VS, windows SDK, and CUDA toolkit got past the error above
- However, I was getting an error during the `CMakeLists` file execution: 

```
Could NOT find Boost (missing: Boost_INCLUDE_DIR system thread date_time
    unit_test_framework python38 chrono numpy38) (Required is at least version
    "1.41")
```

I'm not sure why Boost was not being found even though I was in a Conda env with cmake and boost installed as per the instructions.

I did some poking around and updated CMakeLists to explicitly point to where Boost seems to be installed within the conda env by adding the following to CMakeLists:

```
set( BOOST_ROOT C:/ProgramData/Anaconda3/envs/opti-acoustics/library/include)
set( Boost_INCLUDE_DIR C:/ProgramData/Anaconda3/envs/opti-acoustics/library/include)
set( Boost_LIBRARY_DIR C:/ProgramData/Anaconda3/envs/opti-acoustics/library/lib)
```

After that, the installation process was able to find some of the missing components, but not python38 or numpy38

```
Installing collected packages: pyParallelFDTD
  Running command Running setup.py install for pyParallelFDTD
  running install
  C:\ProgramData\Anaconda3\envs\opti-acoustics\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-38
  creating build\lib.win-amd64-cpython-38\pyParallelFDTD
  copying dist\libPyFDTD\__init__.py -> build\lib.win-amd64-cpython-38\pyParallelFDTD
  running build_ext
  -- Building for: Visual Studio 17 2022
  -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
  -- The CXX compiler identification is MSVC 19.33.31630.0
  -- The CUDA compiler identification is NVIDIA 11.8.89
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Check for working CUDA compiler: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/bin/nvcc.exe - skipped
  -- Detecting CUDA compile features
  -- Detecting CUDA compile features - done
  -- CONDA_PREFIX C:\ProgramData\Anaconda3\envs\opti-acoustics
  -- Found Python: C:/ProgramData/Anaconda3/envs/opti-acoustics/python.exe (found version "3.8.13") found components: Interpreter
  -- Found PythonLibs: C:/Python310/libs/python310.lib (found version "3.10.0")
  -- CONDA_PREFIX C:\ProgramData\Anaconda3\envs\opti-acoustics
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
  -- Looking for pthread_create in pthreads
  -- Looking for pthread_create in pthreads - not found
  -- Looking for pthread_create in pthread
  -- Looking for pthread_create in pthread - not found
  -- Found Threads: TRUE
  CMake Error at C:/ProgramData/Anaconda3/envs/opti-acoustics/Library/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find Boost (missing: python38 numpy38) (found version "1.68.0")
  Call Stack (most recent call first):
    C:/ProgramData/Anaconda3/envs/opti-acoustics/Library/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    C:/ProgramData/Anaconda3/envs/opti-acoustics/Library/share/cmake-3.24/Modules/FindBoost.cmake:2376 (find_package_handle_standard_args)
    CMakeLists.txt:87 (find_package)


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/Sam Wolk/AppData/Local/Temp/pip-req-build-dey1epzu/build/temp.win-amd64-cpython-38/Release/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/Sam Wolk/AppData/Local/Temp/pip-req-build-dey1epzu/build/temp.win-amd64-cpython-38/Release/CMakeFiles/CMakeError.log".
```

If you have any ideas please let me know, as I am planning on using this on a big project and would love to get started ASAP!

**Comment by rantahar** [comment]
Most likely nmake is not looking for libraries in the Anaconda environment. That would be fixed by adding the environment path to the Windows library path (Don't remember how exactly, but this is also not a long term solution).

I could not find nmake on Conda, but that would also help.

**Comment by rantahar** [comment]
Scratch that, it actually looks like it's running CMake from the Conda environment.

**Comment by rantahar** [comment]
Can you try creating the environment with python==3.10?

```
conda create -n PFDTD -c conda-forge python==3.10 boost py-boost cmake numpy scipy
```

**Comment by rantahar** [comment]
Another thing to try: I made a small change to the Windows part of the cmake file in the win32-cmake-dots branch.

Can you check if this helps? The command would be
```
pip install https://github.com/user/repo.git@win32-cmake-dots
```
This would preferably be in the original environment, with python3.8.

**Comment by rantahar** [comment]
Closing, but let me know if the issue continues.
